apiVersion: apps/v1
kind: Deployment
metadata:
  name: aaa
  labels:
    app: aaa
spec:
  replicas: 4
  selector:
    matchLabels:
      app: aaa
  template:
    metadata:
      labels:
        app: aaa
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
