apiVersion: apps/v1
kind: Deployment
metadata:
  name: new
  labels:
    app: new
spec:
  replicas: 4
  selector:
    matchLabels:
      app: new
  template:
    metadata:
      labels:
        app: new
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
